<Project Sdk="Microsoft.NET.Sdk">
  <!-- SPDX-License-Identifier: AGPL-3.0-only -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <PackageId>ArcForges.Native.Otio</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>ArcForges Otio existing native ABI version, build-information and error bindings.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ArcForges.Native.Abstractions/ArcForges.Native.Abstractions.csproj" />
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="../../../LICENSE" Pack="true" PackagePath="/" />
    <None Include="../../../NOTICE.md" Pack="true" PackagePath="/" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>AGPL</LicenceBoundary>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
