# SPDX-License-Identifier: AGPL-3.0-only
include_guard(GLOBAL)

function(arcforges_declare_target_licence target)
    if(NOT ARCFORGES_SPDX_LICENSE STREQUAL "AGPL-3.0-only" OR
       NOT ARCFORGES_LICENCE_BOUNDARY STREQUAL "AGPL")
        message(FATAL_ERROR "AFL001: incorrect native project licence declaration")
    endif()
    set_target_properties(${target} PROPERTIES
        ARCFORGES_SPDX_LICENSE "${ARCFORGES_SPDX_LICENSE}"
        ARCFORGES_LICENCE_BOUNDARY "${ARCFORGES_LICENCE_BOUNDARY}")
endfunction()

function(arcforges_collect_owned_targets directory output)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(external DIRECTORY "${directory}" PROPERTY ARCFORGES_EXTERNAL_TARGETS)
    foreach(target IN LISTS external)
        list(REMOVE_ITEM targets "${target}")
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        arcforges_collect_owned_targets("${child}" nested)
        list(APPEND targets ${nested})
    endforeach()
    set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(arcforges_verify_native_licences)
    arcforges_collect_owned_targets("${CMAKE_SOURCE_DIR}" targets)
    set(rows "[]")
    set(index 0)
    foreach(target IN LISTS targets)
        get_target_property(spdx ${target} ARCFORGES_SPDX_LICENSE)
        get_target_property(boundary ${target} ARCFORGES_LICENCE_BOUNDARY)
        if(NOT spdx STREQUAL "AGPL-3.0-only" OR NOT boundary STREQUAL "AGPL")
            message(FATAL_ERROR "AFL001: missing or incorrect native target licence: ${target}")
        endif()
        get_target_property(source ${target} SOURCE_DIR)
        file(RELATIVE_PATH source "${CMAKE_SOURCE_DIR}" "${source}")
        string(JSON row SET "{}" target "\"${target}\"")
        string(JSON row SET "${row}" sourceDirectory "\"${source}\"")
        string(JSON row SET "${row}" spdxLicense "\"${spdx}\"")
        string(JSON row SET "${row}" licenceBoundary "\"${boundary}\"")
        set(edges "[]")
        set(edge_index 0)
        foreach(property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(links ${target} ${property})
            if(links)
                foreach(link IN LISTS links)
                    # Preserve generator expressions as configure-time graph evidence.
                    # The existing native package audit owns resolved third-party closure.
                    string(REPLACE "\\" "\\\\" escaped "${link}")
                    string(REPLACE "\"" "\\\"" escaped "${escaped}")
                    string(JSON edges SET "${edges}" ${edge_index} "\"${escaped}\"")
                    math(EXPR edge_index "${edge_index} + 1")
                endforeach()
            endif()
        endforeach()
        string(JSON row SET "${row}" references "${edges}")
        string(JSON rows SET "${rows}" ${index} "${row}")
        math(EXPR index "${index} + 1")
    endforeach()
    if(index EQUAL 0)
        message(FATAL_ERROR "AFL004: no owned native targets were evaluated")
    endif()
    execute_process(COMMAND git rev-parse HEAD WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND git status --porcelain WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE changes OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    set(dirty false)
    if(changes)
        set(dirty true)
    endif()
    string(JSON report SET "{}" commit "\"${commit}\"")
    string(JSON report SET "${report}" dirty ${dirty})
    string(JSON report SET "${report}" result "\"passed\"")
    string(JSON report SET "${report}" evidenceClass "\"evaluated-cmake-target-declarations\"")
    string(JSON report SET "${report}" targets "${rows}")
    file(WRITE "${CMAKE_BINARY_DIR}/licence-boundary.json" "${report}\n")
endfunction()
